# API Gateway
server.port=8080

spring.application.name=API-GATEWAY

# Auth Service Route
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/gateway/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Catalog Service Route
spring.cloud.gateway.routes[1].id=catalog-service
spring.cloud.gateway.routes[1].uri=lb://CATALOG-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/gateway/catalog/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# Order Service Route
spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/gateway/orders/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# Admin Service Route
spring.cloud.gateway.routes[3].id=admin-service
spring.cloud.gateway.routes[3].uri=lb://ADMIN-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/gateway/admin/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

# CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# JWT - must match auth-service secret exactly
jwt.secret=ShopSphereSecretKey2024ShopSphereSecretKey2024ShopSphere

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# --- Springdoc / Swagger UI Aggregation ---
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=AUTH-SERVICE
springdoc.swagger-ui.urls[0].url=/gateway/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=CATALOG-SERVICE
springdoc.swagger-ui.urls[1].url=/gateway/catalog/v3/api-docs

springdoc.swagger-ui.urls[2].name=ORDER-SERVICE
springdoc.swagger-ui.urls[2].url=/gateway/orders/v3/api-docs

springdoc.swagger-ui.urls[3].name=ADMIN-SERVICE
springdoc.swagger-ui.urls[3].url=/gateway/admin/v3/api-docs
